version: '2.1'
services:
    rabbitmq:
       image: rabbitmq:3-management
       ports:
         - 15672:15672
         - 5672:5672
       container_name: banco-beer-rabbitmq
       environment:
         - RABBITMQ_HOST=rabbitmq
         - RABBITMQ_USER=guest
         - RABBITMQ_PASS=guest
         - RABBITMQ_DEFAULT_VHOST=/
         - HEALTH_CHECK_CACHE=0
    db:
      image: mysql:5.7
      restart: always
      container_name: banco-beer-mysql
      environment:
        MYSQL_DATABASE: 'bancobeer'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'admin'
        MYSQL_ROOT_PASSWORD: '123'

      ports:
        - '3306:3306'
      expose:
        - '3306'
    banco-beer-api:
        restart: on-failure
        build: banco-beer-api/.
        expose:
        - "8080"
        ports:
        - 8080:8080
        container_name: banco-beer-api
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on:
        - db
        - banco-beer-consume
    banco-beer-consume:
        restart: on-failure
        build: banco-beer-consumer/.
        expose:
        - "8081"
        ports:
        - 8081:8081
        container_name: banco-beer-consume
        network_mode: "host"        
        depends_on:
        - rabbitmq
